CREATE SCHEMA SimplifyHub DEFAULT CHARACTER SET utf8;

CREATE TABLE SimplifyHub.FASHIONISTA (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  EMAIL VARBINARY(100) NOT NULL,
  PASSWORD VARBINARY(50) NOT NULL,
  FRISTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  SEX ENUM('MALE','FEMALE') NOT NULL,
  DOB DATE DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8
  COMMENT = 'Contains the User profile';